- templates/.pa11yci
- templates/gulpfile.coffee
- templates/src/screens/application-noncommercial-group.pug
> Fix accessibility errors found by pa11y

- templates/src/layout.pug
- templates/src/screens/application-noncommercial-group.pug
> Check code with html code sniffer and fix issues

- e2e/index.coffee
- e2e/permit-guidance-flow-regular-person-friends-and-family.coffee
- e2e/permit-guidance-flow-regular-person.coffee
- e2e/permit-guidance-flow-step-1.coffee
- e2e/permit-guidance-flow-step-2.coffee
- templates/protractor.config.coffee
- templates/src/layout.pug
@dubharmonic please take a look at e2e/index.coffee. The tests I wrote for the header functionality are resulting in 'element not displayed errors'. Please let me know if you can see why.
> E2e tests for guidance flow

- templates/src/screens/index.pug
I changed the language because the text supplied was intended for step one. Please let me know if it reads ok.
> Update text on index screen

- templates/.pa11yci
- templates/src/screens/permit-application-view.pug
> pa11y tested admin pages

- frontend/src/app/app.module.ts
- frontend/src/app/application-noncommercial-group/application-noncommercial-group.component.ts
- frontend/src/app/application-noncommercial-group/application-submitted/application-submitted.component.html
- frontend/src/app/application-noncommercial-group/application-submitted/application-submitted.component.spec.ts
- frontend/src/app/application-noncommercial-group/application-submitted/application-submitted.component.ts
> Success page

- frontend/src/app/app.module.ts
- frontend/src/app/application-noncommercial-group/application-noncommercial-group-service.ts
- frontend/src/app/application-noncommercial-group/application-noncommercial-group.component.html
- frontend/src/app/application-noncommercial-group/application-noncommercial-group.component.ts
- frontend/src/app/application-noncommercial-group/application-submitted/application-submitted.component.html
- frontend/src/app/application-noncommercial-group/application-submitted/application-submitted.component.spec.ts
- frontend/src/app/application-noncommercial-group/application-submitted/application-submitted.component.ts
> 256 error response

- server/package.json
- server/test/data/testInputNoncommercial.json
- server/test/noncommercial.js
- test-runner.sh
- add GET test
- add migrate and seed aliases to package.json
- modify test data slightly
- re-enable server tests
- add call to db:migrate and db:seed to test runner script so that server integration tests will run
- added DATABASE_URL env var to CircleCI
> issue #271 - Add db configuration to the build

- .gitignore
- circle.yml
- server/.eslintrc.json
- server/app.es6
- server/package.json
- server/readme.md
- server/test/data/testInputNoncommercial.json
- server/test/noncommercial.js
- test-runner.sh
Adding server side linting to the build process
> Add Server side linting

- frontend/src/app/permit-application-view/permit-application-view.component.html
- frontend/src/app/permit-application-view/permit-application-view.component.scss
- frontend/src/index.html
- frontend/src/sass/_all.scss
- frontend/src/sass/components/_breadcrumbs.scss
- frontend/src/sass/components/_usa-grid.scss
- frontend/src/sass/elements/_backgrounds.scss
- frontend/src/sass/elements/_borders.scss
- frontend/src/sass/elements/_buttons.scss
- frontend/src/sass/elements/_typography.scss
> Implement application list page

- .gitignore
- circle.yml
- run-builds.sh
- server/app.es6
- server/package.json
- server/readme.md
- server/yarn.lock
- test-runner.sh
Adding nyc for code coverage
- added a `coverage` task to package.json
- updated server readme
> 239 add code coverage

- frontend/src/app/app.module.ts
- frontend/src/app/applications/fields/file-upload.component.html
- frontend/src/app/applications/fields/file-upload.component.ts
- frontend/src/app/applications/temporary-outfitters/temporary-outfitters.component.html
- frontend/src/app/applications/temporary-outfitters/temporary-outfitters.component.ts
- frontend/src/assets/img/checkmark.svg
- frontend/src/sass/elements/_input.scss
> 372 implement file upload design

- frontend/src/app/admin/permit-application-view/permit-application-view.component.html
- frontend/src/sass/pages/_application-view.scss
> Applied application view mobile visual design

- .gitignore
- server/dba/migrations/03-modifyName.js
- server/dba/migrations/04-addSigReason.js
- server/dba/migrations/05-removeTimeFields.js
- server/dba/migrations/07-nonCommFieldCleanup.js
- server/dba/migrations/09-noncommChanges.js
- server/dba/migrations/modules/transaction.js
> 427 Added DB Transactions to Sequelize Migrations

- frontend/package.json
- frontend/src/sass/elements/_typography.scss
- frontend/yarn.lock
> 468 updating fonts to arial

- server/dba/migrations/modules/transaction.js
This is a first look at how we can address changes that require DML for the DDL to succeed. As the title indicates, this initial implementation handles string length and allowNull changes.
> 427 pre-migrations for not-null and revised string length changes

- server/app.es6
- server/middlelayer-interaction.es6
- server/package.json
- server/test/data/noncommercialTestData.es6
- server/test/noncommercial.js
Added tests to cover branches of create noncommercial app and update noncommercial app.  Also updated the node engine version for the server to 6.10.3.
> issue 426 server code coverage

- server/app.es6
- server/middlelayer-interaction.es6
- server/package.json
- server/test/misc-server-test.js
- server/vcap-services.es6
additional miscellaneous tests, move vcap services parsing into its own module
> Issue #426, #461

- frontend/src/app/admin/permit-application-list/permit-application-list.component.html
- frontend/src/app/applications/fields/fax.component.html
- frontend/src/sass/pages/_application-list.scss
- server/dba/migrations/11-tempOutfitterChanges.js
- server/dba/migrations/modules/transaction.js
- server/yarn.lock
- Fax number is optional
- UI changes plus migration changes
- added functionality to migration transactions to correctly deal with adding a NOT NULL column
> 498 temp outfitter fields

- frontend/.pa11yci
- frontend/src/app/applications/application-noncommercial-group/application-noncommercial-group.component.html
- frontend/src/app/applications/fields/activity-description.component.html
- frontend/src/app/applications/fields/address.component.html
- frontend/src/app/applications/fields/advertising.component.html
- frontend/src/app/applications/fields/client-charges.component.html
- frontend/src/app/applications/fields/date-time-range.component.html
- frontend/src/app/applications/fields/email.component.html
- frontend/src/app/applications/fields/experience.component.html
- frontend/src/app/applications/fields/fax.component.html
- frontend/src/app/applications/fields/file-upload.component.html
- frontend/src/app/applications/fields/noncommercial-fields.component.html
- frontend/src/app/applications/fields/org-type.component.html
- frontend/src/app/applications/fields/organization-name.component.html
- frontend/src/app/applications/fields/permit-holder-name.component.html
- frontend/src/app/applications/fields/phone-number.component.html
- frontend/src/app/applications/temporary-outfitters/temporary-outfitters.component.html
> 511 add aria required to required fields

- frontend/src/app/_services/application.service.ts
- frontend/src/app/admin/permit-application-list/permit-application-list.component.html
- server/app.es6
- server/noncommercial.es6
- server/package.json
- server/temp-outfitter.es6
- server/test/noncommercial.js
- server/yarn.lock
URL change should have its own PR
> 575 unit tests for saving and retrieving temp outfitter applications

- server/readme.md
- updated server readme with info about how to access swagger api docs and modified env var section to include what the VCAP_SERVICES var should look like
> Issue #540 - update server readme

- frontend/src/app/app-routing.module.ts
- frontend/src/app/applications/application-noncommercial-group/application-noncommercial-group.component.ts
- frontend/src/app/applications/application-submitted/application-submitted.component.html
- frontend/src/app/applications/application-submitted/application-submitted.component.ts
- frontend/src/app/applications/temporary-outfitters/temporary-outfitters.component.ts
> 601 temp outfitter success

- frontend/src/app/applications/fields/activity-description.component.html
- server/dba/migrations/14-updatePartySize.js
- server/json-schemas/activityDescription-fields-schema.es6
- server/models/tempoutfitter-application.es6
- server/test/data/tempOutfitterTestData.es6
- server/yarn.lock
> 659 add hint text to location

- README.md
Update covecoverage badge to master
> Close #801

- frontend/src/app/applications/fields/website.component.html
- frontend/src/app/applications/fields/website.component.ts
- frontend/src/app/applications/temporary-outfitters/temporary-outfitters.component.html
- frontend/src/app/applications/temporary-outfitters/temporary-outfitters.component.ts
…l input if advertising website is empty
> 791 copy website input into advertising website input

- frontend/src/app/_services/auth-guard.service.ts
- frontend/src/app/login/logged-in.component.ts
- server/auth/usda-eauth.es6
- server/email-templates/email-templates.es6
- server/noncommercial.es6
- server/temp-outfitter.es6
- server/vcap-services.es6
> 157 email special use admin

- frontend/src/app/applications/temporary-outfitters/temporary-outfitters.component.html
> add optional text to business name field

- docker/Dockerfile-server
- server/package.json
- server/server-setup.sh
The path to sequelize had changed and snyk-protect was added again, so I have the yarn snyk-protect command checking for FS_DOCKER
> Fix docker

- frontend/src/app/applications/permit-application-list/permit-application-list.component.html
> 918 approve buttons
